package com.thechance.util

object Nationalities {
    val countryToNationality = mapOf(
        "Afghanistan" to "Afghan",
        "Albania" to "Albanian",
        "Algeria" to "Algerian",
        "Argentina" to "Argentine",
        "Australia" to "Australian",
        "Austria" to "Austrian",
        "Bangladesh" to "Bangladeshi",
        "Belgium" to "Belgian",
        "Brazil" to "Brazilian",
        "Canada" to "Canadian",
        "Chile" to "Chilean",
        "China" to "Chinese",
        "Colombia" to "Colombian",
        "Cuba" to "Cuban",
        "Czech Republic" to "Czech",
        "Denmark" to "Danish",
        "Egypt" to "Egyptian",
        "England" to "English",
        "Ethiopia" to "Ethiopian",
        "Finland" to "Finnish",
        "France" to "French",
        "Germany" to "German",
        "Ghana" to "Ghanaian",
        "Greece" to "Greek",
        "Hungary" to "Hungarian",
        "Iceland" to "Icelandic",
        "India" to "Indian",
        "Indonesia" to "Indonesian",
        "Iran" to "Iranian",
        "Iraq" to "Iraqi",
        "Ireland" to "Irish",
        "Israel" to "Israeli",
        "Italy" to "Italian",
        "Jamaica" to "Jamaican",
        "Japan" to "Japanese",
        "Jordan" to "Jordanian",
        "Kenya" to "Kenyan",
        "Kuwait" to "Kuwaiti",
        "Lebanon" to "Lebanese",
        "Malaysia" to "Malaysian",
        "Mexico" to "Mexican",
        "Morocco" to "Moroccan",
        "Nepal" to "Nepalese",
        "Netherlands" to "Dutch",
        "Nigeria" to "Nigerian",
        "Norway" to "Norwegian",
        "Pakistan" to "Pakistani",
        "Peru" to "Peruvian",
        "Philippines" to "Filipino",
        "Poland" to "Polish",
        "Portugal" to "Portuguese",
        "Qatar" to "Qatari",
        "Romania" to "Romanian",
        "Russia" to "Russian",
        "Saudi Arabia" to "Saudi",
        "Scotland" to "Scottish",
        "Serbia" to "Serbian",
        "Singapore" to "Singaporean",
        "South Africa" to "South African",
        "South Korea" to "South Korean",
        "Spain" to "Spanish",
        "Sri Lanka" to "Sri Lankan",
        "Sweden" to "Swedish",
        "Switzerland" to "Swiss",
        "Syria" to "Syrian",
        "Thailand" to "Thai",
        "Tunisia" to "Tunisian",
        "Turkey" to "Turkish",
        "Uganda" to "Ugandan",
        "Ukraine" to "Ukrainian",
        "United Arab Emirates" to "Emirati",
        "United Kingdom" to "British",
        "United States" to "American",
        "Uruguay" to "Uruguayan",
        "Venezuela" to "Venezuelan",
        "Vietnam" to "Vietnamese",
        "Wales" to "Welsh",
        "Yemen" to "Yemeni",
        "Zambia" to "Zambian",
        "Zimbabwe" to "Zimbabwean"
    )
}